### PR TITLE
in memory local dev

### PR DESCRIPTION
**Pull request by padraicbc**
I have implemented a "kind of" filesystem using a map backed up by a slice for ordered searches. A few other optimisations in there like remembering corrected import paths. I had a FS implementaion using the new fs logic  it was actually slower. I may revisit it but will be down the line but this is pretty snappy on any changes. Feel free to change the names of stepOne, stepTwo or any other functions as I didn't spend a great deal of time thinking what they should be!  

Some timings..

```
██████████ Building... Total build took 3.985404062s

Serving site from your "public" directory.
Visit your site at http://localhost:3000/
Total build took 500.312452ms
Total build took 653.355279ms
Total build took 587.369224ms
Total build took 509.11191ms
Total build took 589.162469ms
Total build took 520.187614ms
```

It could be optimised further by maybe adding markers and injecting partial changes to SSR  etc.. but not bad for now.

### CODE REVIEW

**Comment by padraicbc** [comment]
@jimafisk  As I mentioned in #144.  The search for a .js or .mjs in [findJSFile](https://github.com/plentico/plenti/blob/master/cmd/build/gopack.go#L195)  seems to be a game of chance. Am I missing something here or is there a need to be more specific with how the search is implemented?

**Comment by jimafisk** [comment]
> The search for a .js or .mjs in findJSFile seems to be a game of chance.

You're right, this should be more specific or we're rolling the dice on this breaking with Svelte updates or other packages.

I'm super excited about pulling in the mem build! I'm fighting with a broken build due to cgo cross compiling errors: https://github.com/plentico/plenti/issues/148. Once that's fixed, should I pull this in, or do you want to ping me when you're ready?

**Comment by padraicbc** [comment]
I think there is still a small bit of work to exactly mimic the order look for files are searched for in findJsFile gopack as I wasn't sure if I was missing something or if it was just highest order wins. It is 99% there but I want to try out a few cases. There are a good few optimisations all over really so prob best to test it with themes etc...  to make sure all is working but it is hopefully very close to ready.  

I saw #148, not familiar at all with the tool but seems libssl is missing or the wrong version. I wonder if anything [here](https://github.com/elastic/golang-crossbuild) helps?

**Comment by padraicbc** [comment]
Unrelated but this [commit](https://github.com/plentico/plenti/pull/149/commits/a1bc49f8d7a37eaa70bfcef3e70e739e9c70a670) was to fix a really weird bug I couldn't even begin to describe where having a css selector `foo.bar` and then changing one of the matching class names in the html or changing a letter to make it match nothing meant the regex grabbed all the page after the from  `TheMatch` to the end so regexp comlained about unterminated (... 

I wonder if maybe it would pay to extract the script tags when we are processing so we operate on only that part? I can create a parser or we could simply do a dropwhile/takewhile. It would/could also be used for other procesing too...

**Comment by jimafisk** [comment]
If you have a good way to process the `<script>` separately to avoid the regexp edge cases I'm all for it. It would be nice if we could omit the CSS output during SSR entirely (see https://github.com/sveltejs/svelte/issues/3604#issuecomment-748386573) since we're already pulling that out when compiling the `dom`. That would save us some regex headaches.

**Comment by padraicbc** [comment]
You could extract the script portion and the offsets with something like https://gist.github.com/padraicbc/d2305004111de2fbb146a9e4ecbac352 . You can then just work on the script tag itself and there are a few ways to replace the old with the new using the offsets. You could simplify how you find it but using a proper parser would help with attrs etc.. down the line. That is a very quicky put together example so more than likely missed something but the general idea.

**Comment by padraicbc** [comment]
@jimafisk There ended up being a whole load of edge cases which were fun to sort! The latest should be ok to pull in. Still have a lot of ways to optimise but I think maybe extracting the script tag and isolating that might be a good place to start.  https://github.com/padraicbc/parse/blob/master/parse.go#L20 will pull the root level tags passed.  `GetNodes(rd, false, tags "script", "style")` would pull the main style and script tags,  `GetNodes(rd, tryue, tags "script", "style")` woudl pull every one inn the page. 

I have started messing around with [ANTLR](https://www.antlr.org/) there too and think it may be a viable way to create at least a parser to extract parts of the JS we need into a tree or even as a complete parser which could be used to create a compiler in Go altogether.  I have spent just a few hours playing with ANTLR so I may be missing a whole lot but it definitley can be used for some of our needs(like imports) and quite easy to use.

**Comment by jimafisk** [comment]
Woah, I dig the [parse module](https://github.com/padraicbc/parse) you're creating. I just started [reading about ANTLR](https://tomassetti.me/antlr-mega-tutorial/) and it seems really promising.

> it may be a viable way to create at least a parser to extract parts of the JS we need into a tree or even as a complete parser which could be used to create a compiler in Go altogether

That ^ would be insane! Could have applications outside of Plenti as well.

Awesome work on this PR, it's a huge step forward!

**Comment by padraicbc** [comment]
> Woah, I dig the [parse module](https://github.com/padraicbc/parse) you're creating. I just started [reading about ANTLR](https://tomassetti.me/antlr-mega-tutorial/) and it seems really promising.
> 
> > it may be a viable way to create at least a parser to extract parts of the JS we need into a tree or even as a complete parser which could be used to create a compiler in Go altogether
> 
> That ^ would be insane! Could have applications outside of Plenti as well.
> 
> Awesome work on this PR, it's a huge step forward!


No worries. I have a sample of using antlr to modify imports [in this repo](https://github.com/padraicbc/gojsp). The visitor version allows you to return items but you need to make sure to call each method manually. The listener does it all for you but doesn't allow you to return anything so you would store the data in an external structure.
Not sure which is best and couldn't find a go working go implementation of the visitor pattern but it seems to work fine as implemented.  [VisitModuleItems](https://github.com/padraicbc/gojsp/blob/master/cmd/visitor.go#L177) has 2 variation `VisitModuleItems1` and `VisitModuleItems2` to show different ways of doing things, just change/swap the names and they will run.  I think it can do what is required and adding gramar is reasonably simple so hopefully it can!

**Pull request merged**
